name: 'Release'

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - run: |
          git fetch --prune --unshallow --tags -f
          rm -rf .git/hooks/pre-push
      - name: Bump version and push tag
        id: semantic
        uses: docker://ghcr.io/codfish/semantic-release-action:v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          branches: ${{ github.ref_name }}
          plugins: |
            ['@semantic-release/commit-analyzer', '@semantic-release/release-notes-generator', '@semantic-release/github']
      - name: Output
        run: |
          echo "version=${{ steps.semantic.outputs.release-version }}" >> $GITHUB_ENV
          echo "published=${{ steps.semantic.outputs.new-release-published }}" >> $GITHUB_ENV

  publish:
    if: ${{ env.published }}
    runs-on: ubuntu-latest
    needs: release
    env:
      rc-version: ${{ github.sha }}
      version: ${{ env.version }}

    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: setup-scala
        uses: olafurpg/setup-scala@v13
        with:
          java-version: temurin@17.0.5=tgz+https://github.com/adoptium/temurin17-binaries/releases/download/jdk-17.0.5%2B8/OpenJDK17U-jdk_x64_linux_hotspot_17.0.5_8.tar.gz
      - name: import-gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Publish to Nexus
        run: sbt "release release-version ${{ env.version }} with-defaults"
